spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://192.168.56.21:3306/vue_test_dev
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:mariadb://mariadb-galera-service:3306/vue_project_prd
    username: root
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
